name: Daily Flight Check

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create data folder
        run: mkdir -p data

      - name: Download previous database
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: flights-db
          path: data

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_HOST: ${{ secrets.API_HOST }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.chat_id }}
        run: python main.py

      - name: Upload updated database
        uses: actions/upload-artifact@v4
        with:
          name: flights-db
          path: data/flights.db